const initialMensTShirtsAndTankTops = [
  {
    id: "1",
    title: "Поло классичсекое (белое)",
    categoryRu: "Мужские футболки и майки",
    categoryCode: "2",
    collarNeckline: "polo",
    model: "polo",
    sleeves: "short",
    price: 20250,
    originalPrice: 22500,
    pattern: "solid",
    composition: ["viscose"],
    color: "white",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/da870264-624c-4969-98a0-36ccc2c885ec",
      },
    ],
  },
  {
    id: "2",
    title: "Поло классичсекое (черное)",
    categoryRu: "Мужские футболки и майки",
    categoryCode: "2",
    collarNeckline: "polo",
    model: "polo",
    sleeves: "short",
    price: 20250,
    originalPrice: 22500,
    pattern: "solid",
    composition: ["viscose"],
    color: "black",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/f863947b-aab8-4c0c-a026-a439ea1cf912",
      },
      {
        url: "https://shoqansuits.com/static/69c6171a-6289-47ca-b259-8d548021108a",
      },
      {
        url: "https://shoqansuits.com/static/b27e8697-4b08-45f1-ae7e-ce09f2e2ad37",
      },
    ],
  },
  {
    id: "3",
    title: "Поло классичсекое в полоску (черное)",
    categoryRu: "Мужские футболки и майки",
    categoryCode: "2",
    collarNeckline: "polo",
    model: "polo",
    sleeves: "short",
    price: 20250,
    originalPrice: 22500,
    pattern: "solid",
    composition: ["viscose"],
    color: "black",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/ab4f639f-5e77-49cd-82c6-9b17119d7ddd",
      },
    ],
  },
  {
    id: "4",
    title: "Поло классичсекое в полоску (черное)",
    categoryRu: "Мужские футболки и майки",
    categoryCode: "2",
    collarNeckline: "round",
    model: "polo",
    sleeves: "short",
    price: 20250,
    originalPrice: 22500,
    pattern: "solid",
    composition: ["viscose"],
    color: "black",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/ab4f639f-5e77-49cd-82c6-9b17119d7ddd",
      },
    ],
  },
  {
    id: "10",
    title: "Классическая футболка (черная)",
    categoryRu: "Мужские футболки и майки",
    categoryCode: "2",
    collarNeckline: "roundNeck",
    model: "tShirt",
    sleeves: "short",
    price: 18900,
    originalPrice: 21000,
    pattern: "solid",
    composition: ["cotton", "elastane"],
    color: "black",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/fc3b2a67-8d4c-4b19-b8c3-b4cc5ec5a98f",
      },
    ],
  },
  {
    id: "11",
    title: "Лонгслив спортивный (синий)",
    categoryRu: "Мужские футболки и майки",
    categoryCode: "2",
    collarNeckline: "vNeck",
    model: "longSleeve",
    sleeves: "long",
    price: 24500,
    originalPrice: 27500,
    pattern: "striped",
    composition: ["polyester", "spandex"],
    color: "blue",
    discount: "12%",
    images: [
      {
        url: "https://shoqansuits.com/static/8c9b347b-1b1a-4c41-a789-8d59e58e214f",
      },
    ],
  },
  {
    id: "12",
    title: "Поло премиум (темно-зеленое)",
    categoryRu: "Мужские футболки и майки",
    categoryCode: "2",
    collarNeckline: "polo",
    model: "polo",
    sleeves: "short",
    price: 29900,
    originalPrice: 32900,
    pattern: "solid",
    composition: ["cotton", "modal"],
    color: "darkGreen",
    discount: "9%",
    images: [
      {
        url: "https://shoqansuits.com/static/1a56b8b2-bc89-4f4d-932f-13cbb50c53a8",
      },
    ],
  },
  {
    id: "13",
    title: "Худи теплое (серое)",
    categoryRu: "Мужские толстовки",
    categoryCode: "3",
    collarNeckline: "hooded",
    model: "hoodie",
    sleeves: "long",
    price: 32000,
    originalPrice: 36500,
    pattern: "graphic",
    composition: ["polyester", "cotton"],
    color: "gray",
    discount: "12%",
    images: [
      {
        url: "https://shoqansuits.com/static/6e879e73-2d23-4f1a-9e37-b34cc7338b2f",
      },
    ],
  },
  {
    id: "14",
    title: "Рашгард компрессионный (черный)",
    categoryRu: "Спортивная одежда",
    categoryCode: "4",
    collarNeckline: "roundNeck",
    model: "rashGuard",
    sleeves: "long",
    price: 21000,
    originalPrice: 23500,
    pattern: "camouflage",
    composition: ["spandex", "polyester"],
    color: "black",
    discount: "11%",
    images: [
      {
        url: "https://shoqansuits.com/static/d8894f45-5b7a-4e45-bd77-2d9f1c4db27c",
      },
    ],
  },
  {
    id: "15",
    title: "Майка базовая (белая)",
    categoryRu: "Мужские майки",
    categoryCode: "2",
    collarNeckline: "roundNeck",
    model: "tankTop",
    sleeves: "sleeveless",
    price: 16500,
    originalPrice: 19000,
    pattern: "solid",
    composition: ["cotton", "elastane"],
    color: "white",
    discount: "13%",
    images: [
      {
        url: "https://shoqansuits.com/static/3bd3e6fc-7b93-4d7f-8c37-d2636cf8d59e",
      },
    ],
  },
  {
    id: "16",
    title: "Футболка с надписью (красная)",
    categoryRu: "Мужские футболки и майки",
    categoryCode: "2",
    collarNeckline: "roundNeck",
    model: "tShirt",
    sleeves: "short",
    price: 19900,
    originalPrice: 22500,
    pattern: "textPrint",
    composition: ["viscose", "cotton"],
    color: "red",
    discount: "12%",
    images: [
      {
        url: "https://shoqansuits.com/static/77c4a19e-bd99-496d-a645-3e472d88dff5",
      },
    ],
  },
  {
    id: "17",
    title: "Комплект летний (белый и черный)",
    categoryRu: "Мужская одежда",
    categoryCode: "5",
    collarNeckline: "roundNeck",
    model: "set",
    sleeves: "short",
    price: 39900,
    originalPrice: 44900,
    pattern: "solid",
    composition: ["cotton", "polyester"],
    color: "whiteBlack",
    discount: "11%",
    images: [
      {
        url: "https://shoqansuits.com/static/a7d12f6c-9a64-4b7a-83eb-59aef6df4f97",
      },
    ],
  },
  {
    id: "18",
    title: "Футболка с геометрическим узором (бежевый)",
    categoryRu: "Мужские футболки",
    categoryCode: "2",
    collarNeckline: "roundNeck",
    model: "tShirt",
    sleeves: "short",
    price: 18900,
    originalPrice: 21000,
    pattern: "geometry",
    composition: ["cotton", "lycra"],
    color: "beige",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/2b6478e7-9281-4e38-85de-1f7b0b3a69e4",
      },
    ],
  },
  {
    id: "19",
    title: "Трикотажная толстовка (серая)",
    categoryRu: "Мужские толстовки",
    categoryCode: "3",
    collarNeckline: "standCollar",
    model: "hoodie",
    sleeves: "long",
    price: 28900,
    originalPrice: 32900,
    pattern: "textured",
    composition: ["knitwear", "polyester"],
    color: "gray",
    discount: "12%",
    images: [
      {
        url: "https://shoqansuits.com/static/4c96f1d7-7c5d-4b8b-b7de-c7f2a6cf37aa",
      },
    ],
  },
  {
    id: "20",
    title: "Лонгслив трикотажный (темно-серый)",
    categoryRu: "Мужские футболки и майки",
    categoryCode: "2",
    collarNeckline: "roundNeck",
    model: "longSleeve",
    sleeves: "long",
    price: 25900,
    originalPrice: 28900,
    pattern: "solid",
    composition: ["cotton", "knitwear"],
    color: "darkGray",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/1234abcd-5678-efgh-ijkl-9876mnopqrst",
      },
    ],
  },
  {
    id: "21",
    title: "Футболка с принтом (желтая)",
    categoryRu: "Мужские футболки и майки",
    categoryCode: "2",
    collarNeckline: "vNeck",
    model: "tShirt",
    sleeves: "short",
    price: 19500,
    originalPrice: 22000,
    pattern: "textPrint",
    composition: ["polyester", "cotton"],
    color: "yellow",
    discount: "11%",
    images: [
      {
        url: "https://shoqansuits.com/static/a1b2c3d4-e5f6-7890-ghij-klmnopqrstuv",
      },
    ],
  },
  {
    id: "22",
    title: "Поло с полосками (темно-синий)",
    categoryRu: "Мужские футболки и майки",
    categoryCode: "2",
    collarNeckline: "polo",
    model: "polo",
    sleeves: "short",
    price: 31500,
    originalPrice: 34900,
    pattern: "striped",
    composition: ["cotton", "elastane"],
    color: "darkBlue",
    discount: "9%",
    images: [
      {
        url: "https://shoqansuits.com/static/abcdef12-3456-7890-ghij-klmnopqrstuv",
      },
    ],
  },
  {
    id: "23",
    title: "Рашгард компрессионный (белый)",
    categoryRu: "Спортивная одежда",
    categoryCode: "4",
    collarNeckline: "roundNeck",
    model: "rashGuard",
    sleeves: "long",
    price: 21900,
    originalPrice: 24900,
    pattern: "solid",
    composition: ["spandex", "polyamide"],
    color: "white",
    discount: "12%",
    images: [
      {
        url: "https://shoqansuits.com/static/qwerty12-3456-7890-abcd-efghijklmnop",
      },
    ],
  },
  {
    id: "24",
    title: "Майка облегающая (темно-красная)",
    categoryRu: "Мужские майки",
    categoryCode: "2",
    collarNeckline: "roundNeck",
    model: "tankTop",
    sleeves: "sleeveless",
    price: 17800,
    originalPrice: 19900,
    pattern: "solid",
    composition: ["cotton", "spandex"],
    color: "darkRed",
    discount: "11%",
    images: [
      {
        url: "https://shoqansuits.com/static/klmnop12-3456-7890-abcd-efghijklmnop",
      },
    ],
  },
  {
    id: "25",
    title: "Толстовка утепленная (темно-зеленая)",
    categoryRu: "Мужские толстовки",
    categoryCode: "3",
    collarNeckline: "standCollar",
    model: "hoodie",
    sleeves: "long",
    price: 33900,
    originalPrice: 37900,
    pattern: "textured",
    composition: ["wool", "polyester"],
    color: "darkGreen",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/abcd5678-90ef-ghij-klmn-opqrstuvwx",
      },
    ],
  },
  {
    id: "26",
    title: "Комплект летний (голубой и серый)",
    categoryRu: "Мужская одежда",
    categoryCode: "5",
    collarNeckline: "roundNeck",
    model: "set",
    sleeves: "short",
    price: 41900,
    originalPrice: 45900,
    pattern: "solid",
    composition: ["cotton", "polyester"],
    color: "blueGray",
    discount: "9%",
    images: [
      {
        url: "https://shoqansuits.com/static/lmnop123-4567-890a-bcde-fghijklmnop",
      },
    ],
  },
  {
    id: "27",
    title: "Футболка с камуфляжным узором (оливковый)",
    categoryRu: "Мужские футболки",
    categoryCode: "2",
    collarNeckline: "roundNeck",
    model: "tShirt",
    sleeves: "short",
    price: 19500,
    originalPrice: 21900,
    pattern: "camouflage",
    composition: ["cotton", "polyester"],
    color: "olive",
    discount: "11%",
    images: [
      {
        url: "https://shoqansuits.com/static/mnopqr12-3456-7890-abcd-efghijklmnop",
      },
    ],
  },
  {
    id: "28",
    title: "Лонгслив трикотажный (светло-серый)",
    categoryRu: "Мужские футболки и майки",
    categoryCode: "2",
    collarNeckline: "roundNeck",
    model: "longSleeve",
    sleeves: "long",
    price: 26800,
    originalPrice: 29900,
    pattern: "solid",
    composition: ["cotton", "knitwear"],
    color: "lightGray",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/qrstuv12-3456-7890-abcd-efghijklmnop",
      },
    ],
  },
  {
    id: "29",
    title: "Футболка в клетку (белая и черная)",
    categoryRu: "Мужские футболки",
    categoryCode: "2",
    collarNeckline: "roundNeck",
    model: "tShirt",
    sleeves: "short",
    price: 20900,
    originalPrice: 23900,
    pattern: "plaid",
    composition: ["cotton", "elastane"],
    color: "whiteBlack",
    discount: "13%",
    images: [
      {
        url: "https://shoqansuits.com/static/uvwxyz12-3456-7890-abcd-efghijklmnop",
      },
    ],
  },
];

const initialMensTShirtsAndTankTopsFilters = {
  collarNeckline: {
    name: "Воротник/вырез",
    options: [
      { name: "U-вырез", value: "uNeck", count: 0 },
      { name: "V-вырез", value: "vNeck", count: 0 },
      { name: "Вырез-хенли", value: "henleyNeck", count: 0 },
      { name: "Круглый вырез", value: "roundNeck", count: 0 },
      { name: "Отложной", value: "turnDownCollar", count: 0 },
      { name: "Поло", value: "polo", count: 0 },
      { name: "С капюшоном", value: "hooded", count: 0 },
      { name: "Стойка", value: "standCollar", count: 0 },
    ],
  },
  pattern: {
    name: "Узор",
    options: [
      { name: "Геометрия", value: "geometry", count: 0 },
      { name: "Горох", value: "polkaDot", count: 0 },
      { name: "Камуфляж", value: "camouflage", count: 0 },
      { name: "Клетка", value: "plaid", count: 0 },
      { name: "Колорблок", value: "colorBlock", count: 0 },
      { name: "Надпись", value: "textPrint", count: 0 },
      { name: "Однотонный", value: "solid", count: 0 },
      { name: "Полоска", value: "striped", count: 0 },
      { name: "Рисунок", value: "graphic", count: 0 },
      { name: "Текстурный", value: "textured", count: 0 },
    ],
  },
  modelType: {
    name: "Модель",
    options: [
      { name: "Комплект", value: "set", count: 0 },
      { name: "Лонгслив", value: "longSleeve", count: 0 },
      { name: "Майка", value: "tankTop", count: 0 },
      { name: "Поло", value: "polo", count: 0 },
      { name: "Рашгард", value: "rashGuard", count: 0 },
      { name: "Футболка", value: "tShirt", count: 0 },
      { name: "Худи", value: "hoodie", count: 0 },
    ],
  },
  composition: {
    name: "Состав",
    options: [
      { name: "Акрил", value: "acrylic", count: 0 },
      { name: "Бамбук", value: "bamboo", count: 0 },
      { name: "Вискоза", value: "viscose", count: 0 },
      { name: "Жаккард", value: "jacquard", count: 0 },
      { name: "Кашемир", value: "cashmere", count: 0 },
      { name: "Лавсан", value: "lavsan", count: 0 },
      { name: "Лайкра", value: "lycra", count: 0 },
      { name: "Лен", value: "linen", count: 0 },
      { name: "Лиоцелл", value: "lyocell", count: 0 },
      { name: "Модал", value: "modal", count: 0 },
      { name: "Нейлон", value: "nylon", count: 0 },
      { name: "Полиамид", value: "polyamide", count: 0 },
      { name: "Полипропилен", value: "polypropylene", count: 0 },
      { name: "Полиэстер", value: "polyester", count: 0 },
      { name: "Полиэфир", value: "polyether", count: 0 },
      { name: "Рами", value: "ramie", count: 0 },
      { name: "Сорона", value: "sorona", count: 0 },
      { name: "Спандекс", value: "spandex", count: 0 },
      { name: "Тенсель", value: "tencel", count: 0 },
      { name: "Трикотаж", value: "knitwear", count: 0 },
      { name: "Хлопок", value: "cotton", count: 0 },
      { name: "Шелк", value: "silk", count: 0 },
      { name: "Шерсть", value: "wool", count: 0 },
      { name: "Эластан", value: "elastane", count: 0 },
    ],
  },
};

const initialUnderwear = [
  {
    id: "30",
    title: "Боксеры хлопковые (черные)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "boxers",
    fitType: "regularRise",
    setOption: "no",
    price: 17500,
    originalPrice: 19900,
    composition: ["cotton", "elastane"],
    color: "black",
    discount: "12%",
    images: [
      {
        url: "https://shoqansuits.com/static/a1b2c3d4-5678-9101-1121-314151617181",
      },
    ],
  },
  {
    id: "31",
    title: "Брифы из полиэстера (темно-синие)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "briefs",
    fitType: "lowRise",
    setOption: "no",
    price: 14000,
    originalPrice: 15900,
    composition: ["polyester", "spandex"],
    color: "darkBlue",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/b2c3d4e5-6789-0123-4567-891011121314",
      },
    ],
  },
  {
    id: "32",
    title: "Комплект боксеры (черный, белый, серый)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "boxers",
    fitType: "regularRise",
    setOption: "yes",
    price: 49000,
    originalPrice: 54900,
    composition: ["cotton", "polyamide"],
    color: "blackWhiteGray",
    discount: "11%",
    images: [
      {
        url: "https://shoqansuits.com/static/c3d4e5f6-7890-1234-5678-901112131415",
      },
    ],
  },
  {
    id: "33",
    title: "Слипы с низкой посадкой (красные)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "slips",
    fitType: "lowRise",
    setOption: "no",
    price: 15900,
    originalPrice: 17500,
    composition: ["viscose", "spandex"],
    color: "red",
    discount: "9%",
    images: [
      {
        url: "https://shoqansuits.com/static/d4e5f6g7-8901-2345-6789-011213141516",
      },
    ],
  },
  {
    id: "34",
    title: "Боксеры бамбуковые (зеленые)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "boxers",
    fitType: "highRise",
    setOption: "no",
    price: 18900,
    originalPrice: 21500,
    composition: ["bamboo", "cotton"],
    color: "green",
    discount: "12%",
    images: [
      {
        url: "https://shoqansuits.com/static/e5f6g7h8-9012-3456-7890-112131415161",
      },
    ],
  },
  {
    id: "35",
    title: "Стринги эластичные (черные)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "thongs",
    fitType: "lowRise",
    setOption: "no",
    price: 12900,
    originalPrice: 14900,
    composition: ["elastane", "polyester"],
    color: "black",
    discount: "13%",
    images: [
      {
        url: "https://shoqansuits.com/static/f6g7h8i9-0123-4567-8901-213141516171",
      },
    ],
  },
  {
    id: "36",
    title: "Танга с хлопком (белые)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "tanga",
    fitType: "regularRise",
    setOption: "no",
    price: 13500,
    originalPrice: 15500,
    composition: ["cotton", "spandex"],
    color: "white",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/g7h8i9j0-1234-5678-9012-314151617181",
      },
    ],
  },
  {
    id: "37",
    title: "Комплект хипсов (черный, серый)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "hipsters",
    fitType: "regularRise",
    setOption: "yes",
    price: 31900,
    originalPrice: 35900,
    composition: ["polyamide", "cotton"],
    color: "blackGray",
    discount: "11%",
    images: [
      {
        url: "https://shoqansuits.com/static/h8i9j0k1-2345-6789-0123-415161718192",
      },
    ],
  },
  {
    id: "38",
    title: "Кальсоны утепленные (темно-серые)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "longJohns",
    fitType: "highRise",
    setOption: "no",
    price: 22500,
    originalPrice: 24900,
    composition: ["wool", "polyester"],
    color: "darkGray",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/i9j0k1l2-3456-7890-1234-516171819202",
      },
    ],
  },
  {
    id: "39",
    title: "Шорты для сна (голубые)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "shorts",
    fitType: "regularRise",
    setOption: "no",
    price: 16900,
    originalPrice: 18500,
    composition: ["cotton", "viscose"],
    color: "blue",
    discount: "8%",
    images: [
      {
        url: "https://shoqansuits.com/static/j0k1l2m3-4567-8901-2345-617181920212",
      },
    ],
  },
  {
    id: "40",
    title: "Боксеры из вискозы (темно-синие)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "boxers",
    fitType: "regularRise",
    setOption: "no",
    price: 17900,
    originalPrice: 19900,
    composition: ["viscose", "cotton"],
    color: "darkBlue",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/abcd1234-5678-9101-1121-314151617181",
      },
    ],
  },
  {
    id: "41",
    title: "Брифы дышащие (серые)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "briefs",
    fitType: "lowRise",
    setOption: "no",
    price: 13500,
    originalPrice: 15500,
    composition: ["polyamide", "spandex"],
    color: "gray",
    discount: "13%",
    images: [
      {
        url: "https://shoqansuits.com/static/bcde2345-6789-0123-4567-891011121314",
      },
    ],
  },
  {
    id: "42",
    title: "Комплект боксеры (черные, темно-серые)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "boxers",
    fitType: "regularRise",
    setOption: "yes",
    price: 44900,
    originalPrice: 49900,
    composition: ["cotton", "polyester"],
    color: "blackDarkGray",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/cdef3456-7890-1234-5678-901112131415",
      },
    ],
  },
  {
    id: "43",
    title: "Слипы спортивные (синие)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "slips",
    fitType: "lowRise",
    setOption: "no",
    price: 14900,
    originalPrice: 16900,
    composition: ["polyester", "spandex"],
    color: "blue",
    discount: "12%",
    images: [
      {
        url: "https://shoqansuits.com/static/defg4567-8901-2345-6789-011213141516",
      },
    ],
  },
  {
    id: "44",
    title: "Боксеры бамбуковые (темно-зеленые)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "boxers",
    fitType: "highRise",
    setOption: "no",
    price: 19500,
    originalPrice: 22500,
    composition: ["bamboo", "cotton"],
    color: "darkGreen",
    discount: "13%",
    images: [
      {
        url: "https://shoqansuits.com/static/efgh5678-9012-3456-7890-112131415161",
      },
    ],
  },
  {
    id: "45",
    title: "Стринги эластичные (красные)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "thongs",
    fitType: "lowRise",
    setOption: "no",
    price: 12500,
    originalPrice: 14500,
    composition: ["elastane", "polyester"],
    color: "red",
    discount: "14%",
    images: [
      {
        url: "https://shoqansuits.com/static/fghi6789-0123-4567-8901-213141516171",
      },
    ],
  },
  {
    id: "46",
    title: "Танга с хлопком (белые)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "tanga",
    fitType: "regularRise",
    setOption: "no",
    price: 13800,
    originalPrice: 15800,
    composition: ["cotton", "spandex"],
    color: "white",
    discount: "11%",
    images: [
      {
        url: "https://shoqansuits.com/static/ghij7890-1234-5678-9012-314151617181",
      },
    ],
  },
  {
    id: "47",
    title: "Комплект хипсов (темно-серый, бордовый)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "hipsters",
    fitType: "regularRise",
    setOption: "yes",
    price: 32500,
    originalPrice: 36900,
    composition: ["polyamide", "cotton"],
    color: "darkGrayBurgundy",
    discount: "12%",
    images: [
      {
        url: "https://shoqansuits.com/static/hijk8901-2345-6789-0123-415161718192",
      },
    ],
  },
  {
    id: "48",
    title: "Кальсоны утепленные (черные)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "longJohns",
    fitType: "highRise",
    setOption: "no",
    price: 22900,
    originalPrice: 25900,
    composition: ["wool", "polyester"],
    color: "black",
    discount: "11%",
    images: [
      {
        url: "https://shoqansuits.com/static/ijkl9012-3456-7890-1234-516171819202",
      },
    ],
  },
  {
    id: "49",
    title: "Шорты для сна (темно-синие)",
    categoryRu: "Мужское нижнее белье",
    categoryCode: "1732",
    modelType: "shorts",
    fitType: "regularRise",
    setOption: "no",
    price: 17500,
    originalPrice: 19500,
    composition: ["cotton", "viscose"],
    color: "darkBlue",
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/jklm0123-4567-8901-2345-617181920212",
      },
    ],
  },
];

const initialUnderwearFilters = {
  modelType: {
    name: "Модель",
    options: [
      { name: "Боксеры", value: "boxers", count: 4997 },
      { name: "Брифы", value: "briefs", count: 60 },
      { name: "Кальсоны", value: "longJohns", count: 2 },
      { name: "Слипы", value: "slips", count: 504 },
      { name: "Стринги", value: "thongs", count: 110 },
      { name: "Танга", value: "tanga", count: 17 },
      { name: "Хипсы", value: "hipsters", count: 86 },
      { name: "Шорты", value: "shorts", count: 454 },
    ],
  },
  composition: {
    name: "Состав",
    options: [
      { name: "Акрил", value: "acrylic", count: 2 },
      { name: "Бамбук", value: "bamboo", count: 420 },
      { name: "Вискоза", value: "viscose", count: 418 },
      { name: "Полиамид", value: "polyamide", count: 155 },
      { name: "Полиуретан", value: "polyurethane", count: 21 },
      { name: "Полиэстер", value: "polyester", count: 499 },
      { name: "Спандекс", value: "spandex", count: 379 },
      { name: "Хлопок", value: "cotton", count: 5093 },
      { name: "Шелк", value: "silk", count: 60 },
      { name: "Шерсть", value: "wool", count: 8 },
      { name: "Эластан", value: "elastane", count: 2623 },
    ],
  },
  setOption: {
    name: "Комплект",
    options: [
      { name: "Да", value: "yes", count: 1939 },
      { name: "Нет", value: "no", count: 4255 },
    ],
  },
  fitType: {
    name: "Посадка",
    options: [
      { name: "Высокая", value: "highRise", count: 256 },
      { name: "Классическая", value: "regularRise", count: 5702 },
      { name: "Низкая", value: "lowRise", count: 244 },
    ],
  },
};

const initialMensSweatshirtsAndHoodies = [
  {
    id: "50",
    title: "Свитшот классический (черный)",
    categoryRu: "Мужские толстовки и свитшоты",
    categoryCode: "294",
    modelType: "sweatshirt",
    seasonType: "midSeason",
    colorType: "black",
    price: 32900,
    originalPrice: 36900,
    composition: ["cotton", "polyester"],
    discount: "11%",
    images: [
      {
        url: "https://shoqansuits.com/static/a1b2c3d4-5678-9101-1121-314151617181",
      },
    ],
  },
  {
    id: "51",
    title: "Худи утепленное (темно-синий)",
    categoryRu: "Мужские толстовки и свитшоты",
    categoryCode: "294",
    modelType: "hoodie",
    seasonType: "winter",
    colorType: "darkBlue",
    price: 39900,
    originalPrice: 44900,
    composition: ["fleece", "cotton"],
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/b2c3d4e5-6789-0123-4567-891011121314",
      },
    ],
  },
  {
    id: "52",
    title: "Толстовка с капюшоном (серый меланж)",
    categoryRu: "Мужские толстовки и свитшоты",
    categoryCode: "294",
    modelType: "sweatshirtHoodless",
    seasonType: "allSeason",
    colorType: "gray",
    price: 34500,
    originalPrice: 37500,
    composition: ["cotton", "polyamide"],
    discount: "8%",
    images: [
      {
        url: "https://shoqansuits.com/static/c3d4e5f6-7890-1234-5678-901112131415",
      },
    ],
  },
  {
    id: "53",
    title: "Флиска спортивная (темно-зеленая)",
    categoryRu: "Мужские толстовки и свитшоты",
    categoryCode: "294",
    modelType: "fleeceJacket",
    seasonType: "winter",
    colorType: "darkGreen",
    price: 31500,
    originalPrice: 34900,
    composition: ["fleece", "polyester"],
    discount: "9%",
    images: [
      {
        url: "https://shoqansuits.com/static/d4e5f6g7-8901-2345-6789-011213141516",
      },
    ],
  },
  {
    id: "54",
    title: "Свитшот трикотажный (бордовый)",
    categoryRu: "Мужские толстовки и свитшоты",
    categoryCode: "294",
    modelType: "sweatshirt",
    seasonType: "midSeason",
    colorType: "burgundy",
    price: 28900,
    originalPrice: 31900,
    composition: ["cotton", "lycra"],
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/e5f6g7h8-9012-3456-7890-112131415161",
      },
    ],
  },
  {
    id: "55",
    title: "Олимпийка с молнией (светло-серая)",
    categoryRu: "Мужские толстовки и свитшоты",
    categoryCode: "294",
    modelType: "trackJacket",
    seasonType: "midSeason",
    colorType: "lightGray",
    price: 35900,
    originalPrice: 38900,
    composition: ["polyester", "spandex"],
    discount: "8%",
    images: [
      {
        url: "https://shoqansuits.com/static/f6g7h8i9-0123-4567-8901-213141516171",
      },
    ],
  },
  {
    id: "56",
    title: "Худи утепленное (белый)",
    categoryRu: "Мужские толстовки и свитшоты",
    categoryCode: "294",
    modelType: "hoodie",
    seasonType: "winter",
    colorType: "white",
    price: 40900,
    originalPrice: 45900,
    composition: ["cotton", "fleece"],
    discount: "11%",
    images: [
      {
        url: "https://shoqansuits.com/static/g7h8i9j0-1234-5678-9012-314151617181",
      },
    ],
  },
  {
    id: "57",
    title: "Толстовка с молнией (черная)",
    categoryRu: "Мужские толстовки и свитшоты",
    categoryCode: "294",
    modelType: "sweatshirtHoodless",
    seasonType: "allSeason",
    colorType: "black",
    price: 37900,
    originalPrice: 41900,
    composition: ["polyamide", "cotton"],
    discount: "9%",
    images: [
      {
        url: "https://shoqansuits.com/static/h8i9j0k1-2345-6789-0123-415161718192",
      },
    ],
  },
  {
    id: "58",
    title: "Флиска на молнии (оливковый)",
    categoryRu: "Мужские толстовки и свитшоты",
    categoryCode: "294",
    modelType: "fleeceJacket",
    seasonType: "midSeason",
    colorType: "olive",
    price: 33900,
    originalPrice: 37900,
    composition: ["fleece", "polyester"],
    discount: "10%",
    images: [
      {
        url: "https://shoqansuits.com/static/i9j0k1l2-3456-7890-1234-516171819202",
      },
    ],
  },
  {
    id: "59",
    title: "Свитшот утепленный (темно-синий)",
    categoryRu: "Мужские толстовки и свитшоты",
    categoryCode: "294",
    modelType: "sweatshirt",
    seasonType: "winter",
    colorType: "darkBlue",
    price: 42900,
    originalPrice: 47900,
    composition: ["wool", "polyester"],
    discount: "11%",
    images: [
      {
        url: "https://shoqansuits.com/static/j0k1l2m3-4567-8901-2345-617181920212",
      },
    ],
  },
];

const initialMensSweatshirtsAndHoodiesFilters = {
  modelType: {
    name: "Модель",
    options: [
      { name: "Лонгслив", value: "longSleeve", count: 256 },
      { name: "Олимпийка", value: "trackJacket", count: 661 },
      { name: "Свитшот", value: "sweatshirt", count: 3157 },
      { name: "Толстовка", value: "sweatshirtHoodless", count: 4394 },
      { name: "Флиска", value: "fleeceJacket", count: 688 },
      { name: "Худи", value: "hoodie", count: 3640 },
    ],
  },
  composition: {
    name: "Состав",
    options: [
      { name: "Акрил", value: "acrylic", count: 66 },
      { name: "Ангора", value: "angora", count: 7 },
      { name: "Бамбук", value: "bamboo", count: 10 },
      { name: "Велюр", value: "velour", count: 15 },
      { name: "Вискоза", value: "viscose", count: 320 },
      { name: "Искусственная кожа", value: "fauxLeather", count: 6 },
      { name: "Кашемир", value: "cashmere", count: 49 },
      { name: "Лавсан", value: "lavsan", count: 7 },
      { name: "Лайкра", value: "lycra", count: 278 },
      { name: "Лен", value: "linen", count: 36 },
      { name: "Модал", value: "modal", count: 1 },
      { name: "Натуральная кожа", value: "genuineLeather", count: 3 },
      { name: "Нейлон", value: "nylon", count: 53 },
      { name: "Полиамид", value: "polyamide", count: 169 },
      { name: "Полиэстер", value: "polyester", count: 6494 },
      { name: "Спандекс", value: "spandex", count: 324 },
      { name: "Флис", value: "fleece", count: 1000 },
      { name: "Футер", value: "footerFabric", count: 166 },
      { name: "Хлопок", value: "cotton", count: 9010 },
      { name: "Шелк", value: "silk", count: 3 },
      { name: "Шерсть", value: "wool", count: 237 },
      { name: "Эластан", value: "elastane", count: 860 },
    ],
  },
  seasonType: {
    name: "Сезон",
    options: [
      { name: "Демисезон", value: "midSeason", count: 7300 },
      { name: "Зима", value: "winter", count: 2580 },
      { name: "Круглогодичный", value: "allSeason", count: 5759 },
      { name: "Лето", value: "summer", count: 685 },
    ],
  },
  colorType: {
    name: "Цвет",
    options: [
      { name: "Черный", value: "black", count: 5000 },
      { name: "Белый", value: "white", count: 4500 },
      { name: "Серый", value: "gray", count: 3200 },
      { name: "Темно-серый", value: "darkGray", count: 2100 },
      { name: "Светло-серый", value: "lightGray", count: 1800 },
      { name: "Синий", value: "blue", count: 4100 },
      { name: "Темно-синий", value: "darkBlue", count: 2900 },
      { name: "Голубой", value: "lightBlue", count: 1600 },
      { name: "Красный", value: "red", count: 3800 },
      { name: "Бордовый", value: "burgundy", count: 1700 },
      { name: "Оранжевый", value: "orange", count: 900 },
      { name: "Желтый", value: "yellow", count: 1100 },
      { name: "Зеленый", value: "green", count: 2500 },
      { name: "Темно-зеленый", value: "darkGreen", count: 1400 },
      { name: "Светло-зеленый", value: "lightGreen", count: 1000 },
      { name: "Фиолетовый", value: "purple", count: 800 },
      { name: "Розовый", value: "pink", count: 1200 },
      { name: "Бежевый", value: "beige", count: 1600 },
      { name: "Коричневый", value: "brown", count: 1300 },
      { name: "Оливковый", value: "olive", count: 1100 },
    ],
  },
};

export const initialClothes = [
  ...initialMensTShirtsAndTankTops,
  ...initialUnderwear,
  ...initialMensSweatshirtsAndHoodies,
];
export const initialClothesFilters = [
  ...initialMensTShirtsAndTankTopsFilters,
  ...initialUnderwearFilters,
  ...initialMensSweatshirtsAndHoodiesFilters,
];
