export const initialFlowers = [
  {
    id: "1",
    title: "Микс роз (букет из премиальных цветов)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 20250,
    originalPrice: 22500,
    flowerCount: 15,
    flowerHeight: 60,
    discount: "10%",
    features: ["Ароматные", "Гипоаллергенные"],
    images: [
      {
        url: "https://ibb.org.ru/images/2025/02/21/463889941_18461595037033595_7841603756903345320_n.jpg",
      },
    ],
  },
  {
    id: "2",
    title: "Кустовые розы (букет из премиальных цветов)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 38675,
    originalPrice: 45500,
    flowerCount: 25,
    flowerHeight: 70,
    discount: "15%",
    features: ["Экзотические"],
    images: [
      {
        url: "https://ibb.org.ru/images/2025/02/21/465128731_18464301664033595_5556778435451487257_n.jpg",
      },
    ],
  },
  {
    id: "3",
    title: "51 роза (букет из премиальных цветов)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 36575,
    originalPrice: 38500,
    flowerCount: 51,
    flowerHeight: 60,
    discount: "5%",
    features: ["Ароматные"],
    images: [
      {
        url: "https://ibb.org.ru/images/2025/02/21/465208620_18464302867033595_7619758182404541123_n.jpg",
      },
    ],
  },
  {
    id: "4",
    title: "Juliette Roses (букет из премиальных цветов)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["hydrangeas"],
    price: 16200,
    originalPrice: 18000,
    flowerCount: 11,
    flowerHeight: 55,
    discount: "10%",
    features: ["Гипоаллергенные"],
    images: [
      {
        url: "https://ibb.org.ru/images/2025/02/21/457497584_18452816635033595_196479712356391460_n.jpg",
      },
    ],
  },
  {
    id: "5",
    title: "Пионы розовые (букет 7 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["peonies"],
    price: 20000,
    originalPrice: 20000,
    flowerCount: 7,
    flowerHeight: 50,
    discount: "0%",
    features: ["Ароматные"],
    images: [
      {
        url: "https://ibb.org.ru/images/2025/02/21/347393520_526739509492692_3372425150512456820_n.jpg",
      },
    ],
  },
  {
    id: "6",
    title: "Орхидеи фиолетовые (2 ветки)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["orchids"],
    price: 17600,
    originalPrice: 22000,
    flowerCount: 3,
    flowerHeight: 80,
    discount: "20%",
    features: ["Экзотические"],
    images: [
      {
        url: "https://ibb.org.ru/images/2025/02/21/455728685_18449665051033595_3835388020595925492_n.jpg",
      },
    ],
  },
  {
    id: "7",
    title: "Лилии белые (букет 5 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["lilies"],
    price: 13300,
    originalPrice: 14000,
    flowerCount: 5,
    flowerHeight: 65,
    discount: "5%",
    features: ["Гипоаллергенные"],
    images: [
      {
        url: "https://flor2u.ru/images/uploads/conversion/1f9/1f90052c1012489f9e826f9a4b10be85/1f90052c1012489f9e826f9a4b10be85-flor.detail.gallery.jpg",
      },
    ],
  },
  {
    id: "8",
    title: "Гвоздики красные (букет 9 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["carnations"],
    price: 9000,
    originalPrice: 9000,
    flowerCount: 9,
    flowerHeight: 45,
    discount: "0%",
    features: ["Ароматные"],
    images: [
      {
        url: "https://i2.storeland.net/2/8891/188900145/afacdb/buketkrasnyhgvozdik1-jpg.jpg",
      },
    ],
  },
  {
    id: "9",
    title: "Альстромерии микс (букет 11 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["alstroemeria"],
    price: 9500,
    originalPrice: 10000,
    flowerCount: 11,
    flowerHeight: 50,
    discount: "5%",
    features: ["Гипоаллергенные"],
    images: [
      {
        url: "https://ibb.org.ru/images/2025/02/21/456627195_18450486223033595_8577062239828475913_n.jpg",
      },
    ],
  },
  {
    id: "10",
    title: "Белые розы (букет 25 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 14400,
    originalPrice: 16000,
    flowerCount: 21,
    flowerHeight: 70,
    discount: "10%",
    features: ["Бенто-торт"],
    images: [
      {
        url: "https://владивосток.цветы-доставка24.рф/image/cache/catalog/image//catalog/cvety-i-bento/buket-15-roz-kenia-i-bento-tort-300x300.jpg",
      },
      {
        url: "https://pro-buket.kz/wp-content/uploads/2023/02/25-bel-roz__-scaled.webp?ver=2",
      },
    ],
  },

  {
    id: "11",
    title: "Ранункулюсы белые (букет 7 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["ranunculus"],
    price: 16150,
    originalPrice: 19000,
    flowerCount: 7,
    flowerHeight: 55,
    discount: "15%",
    features: ["Экзотические"],
    images: [
      {
        url: "https://pro-buket.kz/wp-content/uploads/2021/08/%D0%91%D0%B5%D0%BB%D1%8B%D0%B5-%D1%80%D0%B0%D0%BD%D1%83%D0%BD%D0%BA%D1%83%D0%BB%D1%8E%D1%81%D1%8B-2-min.webp?ver=2",
      },
    ],
  },
  {
    id: "12",
    title: "Роза красная (букет 21 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 25000,
    originalPrice: 30000,
    flowerCount: 21,
    flowerHeight: 60,
    discount: "10%",
    features: ["Ароматные"],
    images: [
      {
        url: "https://cvetok24.kz/upload/resize_cache/webp/upload/iblock/c78/c7895fa60187a64a1feef100b6afa90c.webp",
      },
    ],
  },
  {
    id: "13",
    title: "Лилии белые (букет 11 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["lily"],
    price: 17500,
    originalPrice: 20000,
    flowerCount: 11,
    flowerHeight: 70,
    discount: "10%",
    features: ["Гипоаллергенные"],
    images: [
      {
        url: "https://flor2u.ru/images/uploads/conversion/e3b/e3b827314cb38e7af3a7bb70c207e687/e3b827314cb38e7af3a7bb70c207e687-flor.detail.gallery.jpg",
      },
    ],
  },
  {
    id: "14",
    title: "Гвоздики розовые (букет 15 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["carnation"],
    price: 11250,
    originalPrice: 15000,
    flowerCount: 15,
    flowerHeight: 50,
    discount: "25%",
    features: ["Ароматные", "Гипоаллергенные"],
    images: [
      {
        url: "https://florcat.ru/upload/delight.webpconverter/upload/resize_cache/iblock/078/500_500_1/0780672841c589a5c40d1e6679611643.jpg.webp?164706808132522",
      },
    ],
  },
  {
    id: "15",
    title: "Роза белая (букет 51 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 45000,
    originalPrice: 50000,
    flowerCount: 51,
    flowerHeight: 70,
    discount: "10%",
    features: ["Ароматные"],
    images: [
      {
        url: "https://cvety.kz/upload/iblock/466/lhl3pqy0b4s03gmp2cbrc808ocy6m0wi/61F0B299_26FF_4027_8693_01785E104F9B.jpeg",
      },
    ],
  },
  {
    id: "16",
    title: "Лилии розовые (букет 21 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["lily"],
    price: 31500,
    originalPrice: 35000,
    flowerCount: 21,
    flowerHeight: 60,
    discount: "10%",
    features: ["Гипоаллергенные", "Экзотические"],
    images: [
      {
        url: "https://content2.flowwow-images.com/data/flowers/524x524/51/1710944365_97583151.jpg",
      },
    ],
  },
  {
    id: "17",
    title: "Ранункулюсы жёлтые (букет 15 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["ranunculus"],
    price: 18000,
    originalPrice: 20000,
    flowerCount: 15,
    flowerHeight: 55,
    discount: "10%",
    features: ["Экзотические"],
    images: [
      {
        url: "https://venusinfleurs.ru/image/catalog/product/4196/4196_1.jpg",
      },
    ],
  },
  {
    id: "18",
    title: "Роза микс (букет 51 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 42500,
    originalPrice: 50000,
    flowerCount: 51,
    flowerHeight: 60,
    discount: "15%",
    features: ["Ароматные", "Экзотические"],
    images: [
      {
        url: "https://www.roza4u.ru/image/cache/catalog/51-roza-mix/51-dlinnaja-roza-miks-1400x1400.jpg",
      },
    ],
  },
  {
    id: "19",
    title: "Гвоздики белые (букет 11 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["carnation"],
    price: 9000,
    originalPrice: 12000,
    flowerCount: 11,
    flowerHeight: 50,
    discount: "25%",
    features: ["Гипоаллергенные"],
    images: [
      {
        url: "https://zakazbuketov.kz/upload/resize_cache/webp/iblock/251/251af18dfa32da5e151f4bb16aef96c8.webp",
      },
    ],
  },
  {
    id: "20",
    title: "Лилии микс (букет 15 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["lily"],
    price: 22500,
    originalPrice: 25000,
    flowerCount: 15,
    flowerHeight: 70,
    discount: "10%",
    features: ["Гипоаллергенные", "Экзотические"],
    images: [
      {
        url: "https://megacvet24.ru/image/cache/catalog/51-liliya-miks-900x900.jpg",
      },
    ],
  },
  {
    id: "21",
    title: "Роза жёлтая (букет 21 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 27500,
    originalPrice: 30000,
    flowerCount: 21,
    flowerHeight: 70,
    discount: "10%",
    features: ["Ароматные"],
    images: [
      {
        url: "https://tribuketa.ru/wp-content/uploads/2017/08/zheltye-rozy-v-krafte.jpg",
      },
    ],
  },
  {
    id: "22",
    title: "Лилии оранжевые (букет 15 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["lily"],
    price: 22500,
    originalPrice: 25000,
    flowerCount: 15,
    flowerHeight: 60,
    discount: "10%",
    features: ["Гипоаллергенные"],
    images: [
      {
        url: "https://megacvet24.ru/image/cache/catalog/35-oranzhevykh-liliy-4-899x899.jpg",
      },
    ],
  },
  {
    id: "23",
    title: "Гвоздики белые (букет 21 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["carnation"],
    price: 15000,
    originalPrice: 20000,
    flowerCount: 21,
    flowerHeight: 50,
    discount: "25%",
    features: ["Гипоаллергенные"],
    images: [
      {
        url: "https://gorod-buketov.ru/wp-content/uploads/2019/05/4324-Buket-belyh-gvozdik.jpg",
      },
    ],
  },
  {
    id: "24",
    title: "Ранункулюсы микс (букет 15 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["ranunculus"],
    price: 18500,
    originalPrice: 22000,
    flowerCount: 15,
    flowerHeight: 55,
    discount: "15%",
    features: ["Экзотические"],
    images: [
      {
        url: "https://shop-cdn1-2.vigbo.tech/shops/29666/products/21251215/images/3-1566aae5936c6c34a667c8f357070992.JPG",
      },
    ],
  },
  {
    id: "25",
    title: "Роза белая (букет 15 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 19500,
    originalPrice: 22000,
    flowerCount: 15,
    flowerHeight: 70,
    discount: "10%",
    features: ["Ароматные"],
    images: [
      {
        url: "https://cvety.kz/upload/resize_cache/iblock/6a8/hc1u2pmv8tuh3jya4w83trytl9jd9knu/435_545_2/WhatsApp-Image-2024_02_10-at-19.41.10-_2_.jpeg",
      },
    ],
  },
  {
    id: "26",
    title: "Лилии жёлтые (букет 11 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["lily"],
    price: 17000,
    originalPrice: 19000,
    flowerCount: 11,
    flowerHeight: 60,
    discount: "10%",
    features: ["Гипоаллергенные", "Экзотические"],
    images: [
      { url: "https://venusinfleurs.ru/image/catalog/product/4161/4161_1.jpg" },
    ],
  },
  {
    id: "27",
    title: "Гвоздики красные (букет 51 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["carnation"],
    price: 38500,
    originalPrice: 45000,
    flowerCount: 51,
    flowerHeight: 50,
    discount: "15%",
    features: ["Ароматные"],
    images: [
      {
        url: "https://dari-cvety.com/assets/images/products/1167/buket-iz-51-krasnyh-gvozdik-2.jpg",
      },
    ],
  },
  {
    id: "28",
    title: "Роза розовая (букет 15 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 20500,
    originalPrice: 23000,
    flowerCount: 15,
    flowerHeight: 70,
    discount: "10%",
    features: ["Ароматные"],
    images: [
      { url: "https://flowers-deliver.ru/wp-content/uploads/2021/12/27-2.jpg" },
    ],
  },
  {
    id: "29",
    title: "Лилии белые (букет 51 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["lily"],
    price: 45000,
    originalPrice: 50000,
    flowerCount: 51,
    flowerHeight: 70,
    discount: "10%",
    features: ["Гипоаллергенные"],
    images: [
      {
        url: "https://rozavam.ru/uploads/photos/3463/thumbs/3463_file_6328585316d55.jpg",
      },
    ],
  },
  {
    id: "30",
    title: "Гвоздики микс (букет 21 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["carnation"],
    price: 15500,
    originalPrice: 18000,
    flowerCount: 21,
    flowerHeight: 50,
    discount: "15%",
    features: ["Гипоаллергенные"],
    images: [
      {
        url: "https://www.roza4u.ru/image/cache/catalog/buket-iz-gvozdik/buket-iz-gvozdik-sochnyj-miks-1400x1400.jpg",
      },
    ],
  },
  {
    id: "31",
    title: "Роза красная (букет 51 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 47000,
    originalPrice: 52000,
    flowerCount: 51,
    flowerHeight: 70,
    discount: "10%",
    features: ["Ароматные"],
    images: [
      {
        url: "https://cvety.kz/upload/resize_cache/iblock/52e/pqh4yxggekxtnqcu7l41c9w6fiienwcq/700_700_1/WhatsApp-Image-2024_01_31-at-13.08.52.jpeg",
      },
    ],
  },
  {
    id: "32",
    title: "Лилии розовые (букет 21 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["lily"],
    price: 33500,
    originalPrice: 37000,
    flowerCount: 21,
    flowerHeight: 60,
    discount: "10%",
    features: ["Гипоаллергенные", "Экзотические"],
    images: [
      {
        url: "https://floralkiki.ru/wp-content/uploads/2024/11/1729441512_12508106.jpg",
      },
    ],
  },
  {
    id: "33",
    title: "Гвоздики жёлтые (букет 15 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["carnation"],
    price: 12000,
    originalPrice: 15000,
    flowerCount: 15,
    flowerHeight: 50,
    discount: "20%",
    features: ["Ароматные", "Гипоаллергенные"],
    images: [
      {
        url: "https://venusinfleurs.ru/image/cache/catalog/product/4066/4066_1-350x350.jpg",
      },
    ],
  },
  {
    id: "34",
    title: "Ранункулюсы красные (букет 11 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["ranunculus"],
    price: 16000,
    originalPrice: 19000,
    flowerCount: 11,
    flowerHeight: 55,
    discount: "15%",
    features: ["Экзотические"],
    images: [
      {
        url: "https://dakotaflora.com/assets/images/products/1442/large/ranunkulus-krasnyi-buket-dakotaflora-1.jpg",
      },
    ],
  },
  {
    id: "35",
    title: "Роза жёлтая (букет 15 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 21000,
    originalPrice: 25000,
    flowerCount: 15,
    flowerHeight: 70,
    discount: "15%",
    features: ["Ароматные"],
    images: [
      { url: "https://dostavka-tsvety.ru/wp-content/uploads/2020/06/19-1.jpg" },
    ],
  },
  {
    id: "36",
    title: "Лилии микс (букет 15 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["lily"],
    price: 23000,
    originalPrice: 26000,
    flowerCount: 15,
    flowerHeight: 70,
    discount: "10%",
    features: ["Гипоаллергенные", "Экзотические"],
    images: [
      {
        url: "https://content2.flowwow-images.com/data/flowers/524x524/45/1657556776_5895345.jpg",
      },
    ],
  },
  {
    id: "37",
    title: "Гвоздики микс (букет 51 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["carnation"],
    price: 39500,
    originalPrice: 46000,
    flowerCount: 51,
    flowerHeight: 50,
    discount: "15%",
    features: ["Гипоаллергенные"],
    images: [
      {
        url: "https://dari-cvety.com/assets/images/products/1169/buket-iz-51-gvozdik-miks.jpg",
      },
    ],
  },
  {
    id: "38",
    title: "Ранункулюсы белые (букет 21 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["ranunculus"],
    price: 29000,
    originalPrice: 32000,
    flowerCount: 21,
    flowerHeight: 55,
    discount: "10%",
    features: ["Экзотические"],
    images: [
      { url: "https://venusinfleurs.ru/image/catalog/product/4195/4195_1.jpg" },
    ],
  },
  {
    id: "39",
    title: "Роза микс (букет 21 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["rose"],
    price: 27000,
    originalPrice: 30000,
    flowerCount: 21,
    flowerHeight: 60,
    discount: "10%",
    features: ["Ароматные", "Экзотические"],
    images: [
      { url: "https://ir-3.ozone.ru/s3/multimedia-7/c1000/6067212547.jpg" },
    ],
  },
  {
    id: "40",
    title: "Лилии красные (букет 11 шт.)",
    categoryRu: "Цветы",
    categoryCode: "flowers",
    bouquetComposition: ["lily"],
    price: 17500,
    originalPrice: 19500,
    flowerCount: 11,
    flowerHeight: 60,
    discount: "10%",
    features: ["Гипоаллергенные"],
    images: [
      { url: "https://venusinfleurs.ru/image/catalog/category/428/428_1.jpg" },
    ],
  },
];

export const initialFilters = {
  bouquetComposition: {
    name: "Состав букета",
    options: [
      { name: "Роза", value: "rose", count: 13 },
      { name: "Лилия", value: "lily", count: 9 },
      { name: "Гвоздика", value: "carnation", count: 7 },
      { name: "Ранункулюсы", value: "ranunculus", count: 5 },
      { name: "Гортензия", value: "hydrangeas", count: 1 },
      { name: "Пионы", value: "peonies", count: 1 },
      { name: "Орхидеи", value: "orchids", count: 1 },
      { name: "Лилии", value: "lilies", count: 1 },
      { name: "Гвоздики", value: "carnations", count: 1 },
      { name: "Альстромерия", value: "alstroemeria", count: 1 },
    ],
  },
  flowerCount: {
    name: "Количество цветов, шт",
    options: [
      { name: "51 шт.", value: 51, count: 7 },
      { name: "21 шт.", value: 21, count: 8 },
      { name: "15 шт.", value: 15, count: 11 },
      { name: "11 шт.", value: 11, count: 7 },
      { name: "7 шт.", value: 7, count: 2 },
      { name: "25 шт.", value: 25, count: 1 },
      { name: "3 шт.", value: 3, count: 1 },
      { name: "5 шт.", value: 5, count: 2 },
      { name: "9 шт.", value: 9, count: 1 },
    ],
  },
  flowerHeight: {
    name: "Высота цветов, см",
    options: [
      { name: "70 см", value: 70, count: 12 },
      { name: "60 см", value: 60, count: 10 },
      { name: "50 см", value: 50, count: 9 },
      { name: "55 см", value: 55, count: 6 },
      { name: "80 см", value: 80, count: 1 },
      { name: "65 см", value: 65, count: 1 },
      { name: "45 см", value: 45, count: 1 },
    ],
  },
  discounts: {
    name: "Скидки",
    options: [
      { name: "10%", value: "10%", count: 21 },
      { name: "20%", value: "20%", count: 2 },
      { name: "15%", value: "15%", count: 9 },
      { name: "25%", value: "25%", count: 3 },
      { name: "5%", value: "5%", count: 3 },
      { name: "0%", value: "0%", count: 2 },
    ],
  },
  features: {
    name: "Особенности",
    options: [
      { name: "Ароматные", value: "ароматные", count: 16 },
      { name: "Гипоаллергенные", value: "гипоаллергенные", count: 19 },
      { name: "Экзотические", value: "экзотические", count: 14 },
      { name: "Бенто-торт", value: "бенто-торт", count: 1 },
    ],
  },
};
